doctrine:
    dbal:
        connections:
            mysql:
                url: '%env(resolve:DATABASE_URL)%' # mysql
            postgres:
                url: '%env(resolve:DATABASE_URL_POSTGRES)%' # postgres
            clickhouse:
                url: '%env(resolve:DATABASE_URL_CLICKHOUSE)%' # clickhouse
                host:     localhost
                port:     8123
                user:     default
                password: ""
                dbname:   default
                driver_class: FOD\DBALClickHouse\Driver
                wrapper_class: FOD\DBALClickHouse\Connection
                options:
                    enable_http_compression: 1
                    max_execution_time: 60
                    sslCA: '/usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt'
            # mongodb:
            #     url: '%env(resolve:DATABASE_URL_MONGODB)%' # mongodb    
        default_connection: mysql

    orm:
        default_entity_manager: mysql
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            clickhouse:

                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            # mongodb:
            #     connection: mongodb
            #     mappings:
            #         App:
            #             is_bundle: false
            #             type: attribute
            #             dir: '%kernel.project_dir%/src/Entity'
            #             prefix: 'App\Entity'
            #             alias: App
        

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
